return {
  [[                        ,                         ]],
  [[                      aGf "                       ]],
  [[                   ,G*^^b   "                     ]],
  [[                 :G^^^^f      `                   ]],
  [[              ,$G^^^^^^b        `.                ]],
  [[            .G^^^^^^^^{           ^.              ]],
  [[          oG^^^^^^^^^^b             ^.            ]],
  [[       .G^^^^^^^^^^^^j                ^.          ]],
  [[     aG^^^^^,oo~^^^^^p                  '.        ]],
  [[   QC^^^^^^^^^^^^^^^j                      .      ]],
  [[    7@Np^^^^^^^^^^^^[                        w    ]],
  [[      7@##Np^^^^^^^:                    ,,,spNC   ]],
  [[        |@####Np^^^f        ,,,epS##SGGGGGG#^     ]],
  [[          |@######NNpS##SGGGGGGGGGGGGGGGGf        ]],
  [[            "@######GGGGGGGGGGGGGGGGGG#\          ]],
  [[              ^@#####GGGGGGGGGGGGGGGf             ]],
  [[                 @###SGGGGGGGGGGG#\               ]],
  [[                   @##bGGGGGGGGM                  ]],
  [[                     %#bGGGGS*                    ]],
  [[                       %NGM^                      ]],
}
